FROM python:3.9-slim as base

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY src /home/src

COPY tests /home/tests

COPY ./.flake8 /home/.flake8

COPY ./noxfile.py /home/noxfile.py

WORKDIR /home

CMD [ "nox" ]